# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.0 [current_project]
read_ip C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo.xci
set_property is_locked true [get_files C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file TP_raw_stub_fifo.hwdef }
synth_design -top TP_raw_stub_fifo -part xc7vx690tffg1761-2 -mode out_of_context
rename_ref -prefix_all TP_raw_stub_fifo_
write_checkpoint -noxdef TP_raw_stub_fifo.dcp
catch { report_utilization -file TP_raw_stub_fifo_utilization_synth.rpt -pb TP_raw_stub_fifo_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.runs/TP_raw_stub_fifo_synth_1/TP_raw_stub_fifo.dcp C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_3/project_3.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
