set_property SRC_FILE_INFO {cfile:C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/pins.xdc rfile:../../../project_2.srcs/constrs_1/imports/new/pins.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/timing.xdc rfile:../../../project_2.srcs/constrs_1/imports/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells slaves/slave6/trigger_top/tracklet_processing_phi0/aurora_test_top/LinkProjPhiPlus/aurora_8b10b_0/inst/gt_wrapper_i/aurora_8b10b_0_multi_gt_i/gt0_aurora_8b10b_0_i/gthe2_i]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells slaves/slave6/trigger_top/tracklet_processing_phi0/aurora_test_top/LinkProjPhiMinus/aurora_8b10b_1/inst/gt_wrapper_i/aurora_8b10b_1_multi_gt_i/gt0_aurora_8b10b_1_i/gthe2_i]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name proc_clk [get_pins slaves/slave6/trigger_top/trigger_clock_synth/inst/clkout2_buf/O]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks proc_clk]
