# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth.xci
# IP: The module: 'trigger_clock_synth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth.xci
# IP: The module: 'trigger_clock_synth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/trigger_clock_synth/trigger_clock_synth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trigger_clock_synth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
