# pins.xdc
# for each I/O signal, define what pin it connects to, and what type of
# signal it is.

#200 MHz system clock
# 'SYSCLK' in the VC709 manual, 'clk200' in this project
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk200_p]
set_property PACKAGE_PIN G18 [get_ports clk200_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk200_n]

# programmable oscillator
# 'USER_CLOCK' in the VC709 manual, 'prog_clk' in this project
set_property IOSTANDARD LVDS [get_ports prog_clk_p]
set_property PACKAGE_PIN AL34 [get_ports prog_clk_n]
set_property IOSTANDARD LVDS [get_ports prog_clk_n]

# USER SMA
# USER_SMA_CLOCK in the VC709 manual, 'sma_clk' in this project
# These are outputs in this design!
set_property IOSTANDARD LVDS [get_ports sma_clk_p]
set_property PACKAGE_PIN AK32 [get_ports sma_clk_n]
set_property IOSTANDARD LVDS [get_ports sma_clk_n]

# MGTREFCLK1 SMA
# SMA_MGT_REFCLK in the VC709 manual, 'gt_clkp, gt_clkn' in this project
# These are externally looped back from the 'sma_clk'
set_property PACKAGE_PIN AK7 [get_ports gt_clkn]

#### FIGURE OUT WHERE THIS GOES
# INST eth/phy/*/gthe2_i LOC=GTHE2_CHANNEL_X1Y13;

# SFP2 - cage labeled 'P2', with a 1 Gbit module.
set_property PACKAGE_PIN AM7 [get_ports gt_rxn]
# SFP2_LOS_LS in the VC709 manual, 'sfp_los' in this project
set_property PACKAGE_PIN AA40 [get_ports sfp_los]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_los]
# SFP2_MOD_DETECT_LST_REFCLK in the VC709 manual, 'sfp_mod_det' in this project
set_property PACKAGE_PIN AA42 [get_ports sfp_mod_det]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_mod_det]
# SFP2_RS0_LS in the VC709 manual, 'sfp_rs0' in this project
set_property PACKAGE_PIN AB38 [get_ports sfp_rs0]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_rs0]
# SFP2_RS1_LS in the VC709 manual, 'sfp_rs1' in this project
set_property PACKAGE_PIN AB39 [get_ports sfp_rs1]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_rs1]
# SFP2_TX_DISABLE_LS_B in the VC709 manual, 'sfp_tx_disable' in this project
set_property PACKAGE_PIN Y42 [get_ports sfp_tx_disable]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_tx_disable]

# LEDs
# GPIO_LED_n_LS in the VC709 manual, 'leds<n>' in this project
set_property PACKAGE_PIN AM39 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[0]}]
set_property PACKAGE_PIN AN39 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[1]}]
set_property PACKAGE_PIN AR37 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[2]}]
set_property PACKAGE_PIN AT37 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[3]}]
set_property PACKAGE_PIN AR35 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[4]}]
set_property PACKAGE_PIN AP41 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[5]}]
set_property PACKAGE_PIN AP42 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[6]}]
set_property PACKAGE_PIN AU39 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {leds[7]}]

# Switch to enable and turn on LED
set_property PACKAGE_PIN AU38 [get_ports en_proc_switch]
set_property IOSTANDARD LVCMOS18 [get_ports en_proc_switch]


set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[23]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[29]}]
set_property MARK_DEBUG true [get_nets slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/rd_en]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[26]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[17]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[30]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[25]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[24]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[19]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[32]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[16]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[33]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[35]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[18]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[27]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[22]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[34]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[31]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[20]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[21]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[28]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[20]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[32]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[18]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[35]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[27]}]
set_property MARK_DEBUG true [get_nets slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/wr_en]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[22]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[30]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[28]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[29]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[16]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[19]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[26]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[31]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[23]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[24]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[34]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[17]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[21]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[33]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[25]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[32]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[26]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[16]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[25]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[23]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[28]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[17]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[19]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[31]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[20]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[30]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[33]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[21]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[29]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[34]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[24]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[22]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[18]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[27]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[35]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list O_BUFG]]
set_property port_width 36 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[0]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[1]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[2]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[3]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[4]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[5]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[6]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[7]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[8]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[9]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[10]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[11]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[12]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[13]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[14]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[15]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[16]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[17]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[18]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[19]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[20]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[21]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[22]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[23]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[24]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[25]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[26]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[27]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[28]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[29]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[30]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[31]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[32]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[33]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[34]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/dout[35]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list ipb_clk]]
set_property port_width 36 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[0]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[1]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[2]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[3]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[4]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[5]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[6]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[7]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[8]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[9]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[10]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[11]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[12]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[13]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[14]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[15]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[16]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[17]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[18]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[19]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[20]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[21]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[22]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[23]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[24]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[25]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[26]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[27]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[28]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[29]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[30]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[31]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[32]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[33]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[34]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/din[35]}]]
create_debug_port u_ila_0 probe
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[0]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[1]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[2]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[3]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[4]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/numberL1[5]}]]
create_debug_port u_ila_0 probe
set_property port_width 6 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[0]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[1]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[2]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[3]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[4]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stub_cnt_reg__0[5]}]]
create_debug_port u_ila_0 probe
set_property port_width 36 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[0]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[1]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[2]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[3]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[4]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[5]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[6]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[7]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[8]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[9]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[10]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[11]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[12]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[13]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[14]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[15]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[16]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[17]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[18]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[19]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[20]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[21]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[22]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[23]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[24]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[25]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[26]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[27]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[28]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[29]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[30]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[31]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[32]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[33]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[34]} {slaves/slave6/trigger_top/tracklet_processing_phi0/R1Route1/stubin_hold[35]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/rd_en]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list slaves/slave6/trigger_top/tracklet_processing_phi0/R1Link1/raw_stubs/wr_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets O_BUFG]
