# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo.xci
# IP: The module: 'TP_raw_stub_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo/TP_raw_stub_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP_raw_stub_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP_raw_stub_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo.xci
# IP: The module: 'TP_raw_stub_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo/TP_raw_stub_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP_raw_stub_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ZhengchengTao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/TP_raw_stub_fifo/TP_raw_stub_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP_raw_stub_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
