set_false_path -from [get_pins slaves/slave6/trigger_top/TC/TPAR_L1D3L2D3/Tracklet/RAM_reg/CLKARDCLK] -to [get_pins {slaves/slave6/trigger_top/TC/reader1/read_out_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v7_bi_fifo.fblk/gextw[*].gnll_fifo.inst_extd/gonep.inst_prim/gf36e1_inst.sngfifo36e1/WREN}]
set_false_path -from [get_pins slaves/slave6/trigger_top/TC/TPAR_L1D3L2D3/Tracklet/RAM_reg/CLKARDCLK] -to [get_pins {slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[10]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[11]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[12]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[13]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[14]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[15]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[16]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[17]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[18]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[19]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[1]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[20]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[21]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[22]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[23]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[24]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[25]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[26]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[27]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[28]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[29]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[2]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[30]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[31]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[3]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[4]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[5]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[6]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[7]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[8]/CE slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[9]/CE}]
set_false_path -from [get_pins slaves/slave6/trigger_top/TC/TPAR_L1D3L2D3/Tracklet/RAM_reg/CLKARDCLK] -to [get_pins {slaves/slave6/trigger_top/TC/reader1/rd_data_reg_reg[*]/D}]

set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[3]}]
set_property MARK_DEBUG true [get_nets slaves/slave6/trigger_top/en_proc_2]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list slaves/slave6/trigger_top/proc_clk]]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[0]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[1]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[2]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[3]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[4]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[5]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[6]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[7]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[8]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[9]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[10]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[11]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[12]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[13]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[14]} {slaves/slave6/trigger_top/commy/PT_Plus_D3/aurora_test_top/LinkProjPhiPlus/data_io/DOBDO[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list slaves/slave6/trigger_top/en_proc_2]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_proc_clk]
