set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/WEBWE[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[16]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[30]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[32]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[25]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[17]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[35]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[31]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[26]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[20]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[22]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[24]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[34]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[21]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[19]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[29]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[23]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[27]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[28]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[18]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[33]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[8]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/WEBWE[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[15]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[2]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[4]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[7]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[16]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[5]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[12]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[13]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[10]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[0]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[14]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[3]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[6]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[11]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[9]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[1]}]
set_property MARK_DEBUG true [get_nets {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[8]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list slaves/slave6/trigger_top/proc_clk]]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[0]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[1]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[2]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[3]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[4]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[5]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/WEBWE[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 17 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[0]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[1]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[2]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[3]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[4]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[5]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[6]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[7]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[8]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[9]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[10]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[11]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[12]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[13]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[14]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[15]} {slaves/slave6/trigger_top/commy/TPROJ_FromPlus_L1D3L2D3_L3/Projection/data_in_dly[16]}]]
create_debug_port u_ila_0 probe
set_property port_width 36 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[0]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[1]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[2]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[3]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[4]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[5]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[6]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[7]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[8]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[9]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[10]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[11]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[12]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[13]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[14]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[15]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[16]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[17]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[18]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[19]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[20]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[21]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[22]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[23]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[24]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[25]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[26]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[27]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[28]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[29]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[30]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[31]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[32]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[33]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[34]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/Q[35]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/WEBWE[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[0]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[1]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[2]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[3]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[4]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[5]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[6]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[7]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[8]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[9]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[10]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[11]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[12]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[13]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[14]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/D[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[0]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[1]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[2]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[3]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[4]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRARDADDR[5]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[0]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[1]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[2]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[3]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[4]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[5]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[6]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[7]} {slaves/slave6/trigger_top/commy/TPROJ_ToPlus_L1D3L2D3_L3/Projection/ADDRBWRADDR[8]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_proc_clk]
