# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.0 [current_project]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/trigger_clock_synth_synth_1/trigger_clock_synth.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/trigger_clock_synth_synth_1/trigger_clock_synth.dcp]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/aurora_8b10b_0_synth_1/aurora_8b10b_0.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/aurora_8b10b_0_synth_1/aurora_8b10b_0.dcp]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/aurora_8b10b_1_synth_1/aurora_8b10b_1.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/aurora_8b10b_1_synth_1/aurora_8b10b_1.dcp]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/gig_ethernet_pcs_pma_0_synth_1/gig_ethernet_pcs_pma_0.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/gig_ethernet_pcs_pma_0_synth_1/gig_ethernet_pcs_pma_0.dcp]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/link_axis_data_fifo_synth_1/link_axis_data_fifo.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/link_axis_data_fifo_synth_1/link_axis_data_fifo.dcp]
add_files -quiet E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/TP_raw_stub_fifo_synth_1/TP_raw_stub_fifo.dcp
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.runs/TP_raw_stub_fifo_synth_1/TP_raw_stub_fifo.dcp]
read_verilog -library xil_defaultlib {
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/reg_ce2.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/aurora_8b10b_cdc_sync_exdes.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/aurora_io_block.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/aurora_8b10b_support_reset_logic.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/aurora_8b10b_standard_cc_module.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/aurora_8b10b_clock_module.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Aurora_Channel_1.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Aurora_Channel_0.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TrackletProjections.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/Memory.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Aurora_test_vc709.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/VMStubs.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/VMRouters.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/VMProj.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TracksPars.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TrackProj.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TrackPars.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TrackletCombiner.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TrackFit.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/TE.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/StubsByLayer.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/StubPairs.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/ProjRouter.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/MatchEngine.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/MatchCombiner.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/Match.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/LayerRouter.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/InputLink.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/FullMatches.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/AllStubs.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/AllProj.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/Tracklet_processing.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/imports/sim5/IPB_IO_interface.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/new/verilog_trigger_top.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Reset_Synchronizer.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/CLK_Counter.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Link_Interface.v
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/new/Data_FSM.v
}
read_vhdl -library xil_defaultlib {
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/ipbus_trans_decl.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/ipbus_package.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_tx_mux.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_txtransactor_if_simple.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_status_buffer.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_rxtransactor_if_simple.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_rxram_shim.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_rxram_mux.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_rarp_block.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_packet_parser.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_ipaddr_block.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_dualportram_tx.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_dualportram_rx.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_dualportram.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_do_rx_reset.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_clock_crossing_if.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_byte_sum.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_build_status.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_build_resend.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_build_ping.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_build_payload.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_build_arp.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_buffer_selector.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/transactor_sm.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/transactor_if.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/transactor_cfg.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/hdl/ipbus_addr_decode.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/hdl/clock_div.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ethernet/hdl/EthernetCRC.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_trigger_top.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_reg.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_ram.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_pkt_ctr.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_peephole_ram.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/slaves/hdl/ipbus_ctrlreg.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/udp_if_flat.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/trans_arb.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/transactor.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/stretcher.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/ipbus_fabric.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ethernet/hdl/soft_emac_AXI4.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ethernet/hdl/emac_hostbus_decl.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ipbus_core/hdl/ipbus_ctrl.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/hdl/slaves.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/hdl/clocks_7s_serdes.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ethernet/hdl/eth_7s_1000basex_new.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/top/top_vc709_basex.vhd
  E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/imports/sources_1/VC709_ipbus/ipbus/ethernet/hdl/mac_arbiter_decl.vhd
}
read_xdc E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/pins.xdc
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/pins.xdc]

read_xdc E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/timing.xdc
set_property used_in_implementation false [get_files E:/ztaotest/VC709_IPbus_trigger/project_2/project_2.srcs/constrs_1/imports/new/timing.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7vx690tffg1761-2
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
