# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo.xci
# IP: The module: 'link_axis_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo/link_axis_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo/link_axis_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo.xci
# IP: The module: 'link_axis_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo/link_axis_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Zhengcheng Tao/Documents/VC709_IPbus_trigger/project_2/project_2.srcs/sources_1/ip/link_axis_data_fifo/link_axis_data_fifo/link_axis_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'link_axis_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
